# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on:
  push:
    branches: [ master ]
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./web-app

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'

   
    - name: Install
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Build
      run: npm run build
      working-directory: ${{env.working-directory}}

    - name: Test
      run: npm run test
      working-directory: ${{env.working-directory}}

    - name: Firebase Install
      run: npm install -g firebase-tools

    - name: Firebase Deploy
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      working-directory: ${{env.working-directory}}
      
     

 
