
name: Continuous Integration

on:
  push:
    branches: [ master ]
 
jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./web-app

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'

   
    - name: Install
      run: npm install
      working-directory: ${{env.working-directory}}

    - name: Build
      run: npm run build
      working-directory: ${{env.working-directory}}

    - name: Test
      run: npm run test
      working-directory: ${{env.working-directory}}

    - name: Firebase Install
      run: npm install -g firebase-tools

    - name: Firebase Deploy
      run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
      working-directory: ${{env.working-directory}}
      
     

 
